version: '3'
services:
  mainapp:
    image: k8s-condition-demo-mainapp:latest
    build:
      context: mainapp
    ports:
      - 8001:8001

  setupwizard:
    image: k8s-condition-demo-setupwizard:latest
    build:
      context: setupwizard
    ports:
      - 8000:8000
